export const DASHBOARD_LINKS = [
    {
        name: "In Progress",
        icon: "bi-clock",
        link: "/in-progress",
    },
    {
        name: "Live Auctions",
        icon: "bi-lightning",
        link: "/live-auctions",
    },
    {
        name: "Auction Comments",
        icon: "bi-chat",
        link: "/comments",
    },
    {
        name: "Past Listings",
        icon: "bi-archive",
        link: "/past-listings",
    },
];

export const DUMMY_COMMENTS = [
    {
        name: "Andrew G.",
        date: "Apr 2024",
        comment:
            "I have bought and sold on other auction websites, but Cars & Bids definitely tops everyone in customer service.",
        rating: 5,
    },
    {
        name: "Sophia L.",
        date: "Jan 2024",
        comment: "Fast, easy, and hassle-free experience. Highly recommended!",
        rating: 5,
    },
    {
        name: "Michael B.",
        date: "Feb 2024",
        comment:
            "Got a great price for my car and the process was super smooth!",
        rating: 5,
    },
];

export const BODY_STYLES = [
    "Coupe",
    "Convertible",
    "Hatchback",
    "Sedan",
    "SUV/Crossover",
    "Truck",
    "Van/Minivan",
    "Wagon",
];

export const DUMMY_CARS = [
    {
        id: 1,
        year_model: null,
        make: "Tesla",
        model: "Model 3",
        description: "~20000, Dual Electric Motors, undefined",
        starting_bid: 20000,
        created_at: "2025-03-03T13:17:34.000+00:00",
        status: false,
        start_time: "2025-03-03T20:16:00.000+00:00",
        end_time: "2025-03-10T20:16:00.000+00:00",
        f_user_id: {
            id: 2,
            username: "user1",
            bio: "this is a test",
            admin: false,
            password: "a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=",
            email: "user1@gmail.com",
            created_at: "2025-03-03T07:52:38.000+00:00",
            balance: 1000,
            image_url:
                "https://res.cloudinary.com/dppk10edk/image/upload/v1740988357/avatar_wxim4o.jpg",
        },
        mileage: 20000,
        interial_color: "White",
        exterior_color: "Black",
        engine: "Dual Electric Motors",
        drive_type: null,
        body_style: "Sedan",
        doors: null,
        condition: null,
        price: null,
        location: null,
        transmission: "automatic",
        fuel_type: null,
        equipment:
            "Electronics Package (navigation system, blind spot monitoring system with cross-traffic alert); 19-inch carbon fiber wheels; Brembo braking system",
        flaws: "Some scratches around the exterior; Chip in the windshield; Dings on the roof",
        modifications:
            "Paint protection film applied to exterior panels; Exterior stripes deleted; Shelby shift knob",
        vin: null,
    },
    {
        id: 2,
        year_model: null,
        make: "Tesla",
        model: "Model 3",
        description: "~20000, Dual Electric Motors, undefined",
        starting_bid: 20000,
        created_at: "2025-03-03T13:17:34.000+00:00",
        status: false,
        start_time: "2025-03-03T20:16:00.000+00:00",
        end_time: "2025-03-10T20:16:00.000+00:00",
        f_user_id: {
            id: 2,
            username: "user1",
            bio: "this is a test",
            admin: false,
            password: "a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=",
            email: "user1@gmail.com",
            created_at: "2025-03-03T07:52:38.000+00:00",
            balance: 1000,
            image_url:
                "https://res.cloudinary.com/dppk10edk/image/upload/v1740988357/avatar_wxim4o.jpg",
        },
        mileage: 20000,
        interial_color: "White",
        exterior_color: "Black",
        engine: "Dual Electric Motors",
        drive_type: null,
        body_style: "Sedan",
        doors: null,
        condition: null,
        price: null,
        location: null,
        transmission: "automatic",
        fuel_type: null,
        equipment:
            "Electronics Package (navigation system, blind spot monitoring system with cross-traffic alert); 19-inch carbon fiber wheels; Brembo braking system",
        flaws: "Some scratches around the exterior; Chip in the windshield; Dings on the roof",
        modifications:
            "Paint protection film applied to exterior panels; Exterior stripes deleted; Shelby shift knob",
        vin: null,
    },
    {
        id: 301,
        year_model: null,
        make: "Tesla",
        model: "Model 3",
        description: "~20000, Dual Electric Motors, undefined",
        starting_bid: 20000,
        created_at: "2025-03-03T13:17:34.000+00:00",
        status: false,
        start_time: "2025-03-03T20:16:00.000+00:00",
        end_time: "2025-03-10T20:16:00.000+00:00",
        f_user_id: {
            id: 2,
            username: "user1",
            bio: "this is a test",
            admin: false,
            password: "a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=",
            email: "user1@gmail.com",
            created_at: "2025-03-03T07:52:38.000+00:00",
            balance: 1000,
            image_url:
                "https://res.cloudinary.com/dppk10edk/image/upload/v1740988357/avatar_wxim4o.jpg",
        },
        mileage: 20000,
        interial_color: "White",
        exterior_color: "Black",
        engine: "Dual Electric Motors",
        drive_type: null,
        body_style: "Sedan",
        doors: null,
        condition: null,
        price: null,
        location: null,
        transmission: "automatic",
        fuel_type: null,
        equipment:
            "Electronics Package (navigation system, blind spot monitoring system with cross-traffic alert); 19-inch carbon fiber wheels; Brembo braking system",
        flaws: "Some scratches around the exterior; Chip in the windshield; Dings on the roof",
        modifications:
            "Paint protection film applied to exterior panels; Exterior stripes deleted; Shelby shift knob",
        vin: null,
    },
    {
        id: 302,
        year_model: null,
        make: "Tesla",
        model: "Model 3",
        description: "~20000, Dual Electric Motors, undefined",
        starting_bid: 20000,
        created_at: "2025-03-03T13:17:34.000+00:00",
        status: false,
        start_time: "2025-03-03T20:16:00.000+00:00",
        end_time: "2025-03-10T20:16:00.000+00:00",
        f_user_id: {
            id: 2,
            username: "user1",
            bio: "this is a test",
            admin: false,
            password: "a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=",
            email: "user1@gmail.com",
            created_at: "2025-03-03T07:52:38.000+00:00",
            balance: 1000,
            image_url:
                "https://res.cloudinary.com/dppk10edk/image/upload/v1740988357/avatar_wxim4o.jpg",
        },
        mileage: 20000,
        interial_color: "White",
        exterior_color: "Black",
        engine: "Dual Electric Motors",
        drive_type: null,
        body_style: "Sedan",
        doors: null,
        condition: null,
        price: null,
        location: null,
        transmission: "automatic",
        fuel_type: null,
        equipment:
            "Electronics Package (navigation system, blind spot monitoring system with cross-traffic alert); 19-inch carbon fiber wheels; Brembo braking system",
        flaws: "Some scratches around the exterior; Chip in the windshield; Dings on the roof",
        modifications:
            "Paint protection film applied to exterior panels; Exterior stripes deleted; Shelby shift knob",
        vin: null,
    },
    {
        id: 303,
        year_model: null,
        make: "Tesla",
        model: "Model 3",
        description: "~20000, Dual Electric Motors, undefined",
        starting_bid: 20000,
        created_at: "2025-03-03T13:17:34.000+00:00",
        status: false,
        start_time: "2025-03-03T20:16:00.000+00:00",
        end_time: "2025-03-10T20:16:00.000+00:00",
        f_user_id: {
            id: 2,
            username: "user1",
            bio: "this is a test",
            admin: false,
            password: "a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=",
            email: "user1@gmail.com",
            created_at: "2025-03-03T07:52:38.000+00:00",
            balance: 1000,
            image_url:
                "https://res.cloudinary.com/dppk10edk/image/upload/v1740988357/avatar_wxim4o.jpg",
        },
        mileage: 20000,
        interial_color: "White",
        exterior_color: "Black",
        engine: "Dual Electric Motors",
        drive_type: null,
        body_style: "Sedan",
        doors: null,
        condition: null,
        price: null,
        location: null,
        transmission: "automatic",
        fuel_type: null,
        equipment:
            "Electronics Package (navigation system, blind spot monitoring system with cross-traffic alert); 19-inch carbon fiber wheels; Brembo braking system",
        flaws: "Some scratches around the exterior; Chip in the windshield; Dings on the roof",
        modifications:
            "Paint protection film applied to exterior panels; Exterior stripes deleted; Shelby shift knob",
        vin: null,
    },
    {
        id: 304,
        year_model: null,
        make: "Tesla",
        model: "Model 3",
        description: "~20000, Dual Electric Motors, undefined",
        starting_bid: 20000,
        created_at: "2025-03-03T13:17:34.000+00:00",
        status: false,
        start_time: "2025-03-03T20:16:00.000+00:00",
        end_time: "2025-03-10T20:16:00.000+00:00",
        f_user_id: {
            id: 2,
            username: "user1",
            bio: "this is a test",
            admin: false,
            password: "a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=",
            email: "user1@gmail.com",
            created_at: "2025-03-03T07:52:38.000+00:00",
            balance: 1000,
            image_url:
                "https://res.cloudinary.com/dppk10edk/image/upload/v1740988357/avatar_wxim4o.jpg",
        },
        mileage: 20000,
        interial_color: "White",
        exterior_color: "Black",
        engine: "Dual Electric Motors",
        drive_type: null,
        body_style: "Sedan",
        doors: null,
        condition: null,
        price: null,
        location: null,
        transmission: "automatic",
        fuel_type: null,
        equipment:
            "Electronics Package (navigation system, blind spot monitoring system with cross-traffic alert); 19-inch carbon fiber wheels; Brembo braking system",
        flaws: "Some scratches around the exterior; Chip in the windshield; Dings on the roof",
        modifications:
            "Paint protection film applied to exterior panels; Exterior stripes deleted; Shelby shift knob",
        vin: null,
    },
    {
        id: 305,
        year_model: null,
        make: "Tesla",
        model: "Model 3",
        description: "~20000, Dual Electric Motors, undefined",
        starting_bid: 20000,
        created_at: "2025-03-03T13:17:34.000+00:00",
        status: false,
        start_time: "2025-03-03T20:16:00.000+00:00",
        end_time: "2025-03-10T20:16:00.000+00:00",
        f_user_id: {
            id: 2,
            username: "user1",
            bio: "this is a test",
            admin: false,
            password: "a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=",
            email: "user1@gmail.com",
            created_at: "2025-03-03T07:52:38.000+00:00",
            balance: 1000,
            image_url:
                "https://res.cloudinary.com/dppk10edk/image/upload/v1740988357/avatar_wxim4o.jpg",
        },
        mileage: 20000,
        interial_color: "White",
        exterior_color: "Black",
        engine: "Dual Electric Motors",
        drive_type: null,
        body_style: "Sedan",
        doors: null,
        condition: null,
        price: null,
        location: null,
        transmission: "automatic",
        fuel_type: null,
        equipment:
            "Electronics Package (navigation system, blind spot monitoring system with cross-traffic alert); 19-inch carbon fiber wheels; Brembo braking system",
        flaws: "Some scratches around the exterior; Chip in the windshield; Dings on the roof",
        modifications:
            "Paint protection film applied to exterior panels; Exterior stripes deleted; Shelby shift knob",
        vin: null,
    },
    {
        id: 306,
        year_model: null,
        make: "Tesla",
        model: "Model 3",
        description: "~20000, Dual Electric Motors, undefined",
        starting_bid: 20000,
        created_at: "2025-03-03T13:17:34.000+00:00",
        status: false,
        start_time: "2025-03-03T20:16:00.000+00:00",
        end_time: "2025-03-10T20:16:00.000+00:00",
        f_user_id: {
            id: 2,
            username: "user1",
            bio: "this is a test",
            admin: false,
            password: "a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=",
            email: "user1@gmail.com",
            created_at: "2025-03-03T07:52:38.000+00:00",
            balance: 1000,
            image_url:
                "https://res.cloudinary.com/dppk10edk/image/upload/v1740988357/avatar_wxim4o.jpg",
        },
        mileage: 20000,
        interial_color: "White",
        exterior_color: "Black",
        engine: "Dual Electric Motors",
        drive_type: null,
        body_style: "Sedan",
        doors: null,
        condition: null,
        price: null,
        location: null,
        transmission: "automatic",
        fuel_type: null,
        equipment:
            "Electronics Package (navigation system, blind spot monitoring system with cross-traffic alert); 19-inch carbon fiber wheels; Brembo braking system",
        flaws: "Some scratches around the exterior; Chip in the windshield; Dings on the roof",
        modifications:
            "Paint protection film applied to exterior panels; Exterior stripes deleted; Shelby shift knob",
        vin: null,
    },
];


export const DUMMY_QA = [
    {
        id: 1,
        askerName: "dhb2",
        askerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        askerScore: "+22",
        question:
            "Hello - What is the actual color of the car (under the wrap)? I don see it in the invoice you attached. Thanks!",
        sellerName: "Raymondu.lu",
        sellerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        answer: "Hi great question, it is not that difficult to take off the wrap...",
    },
    {
        id: 2,
        askerName: "Cinn",
        askerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        askerScore: "+2",
        question: "So... how difficult would it be to remove the green wrap!?",
        sellerName: "Raymondu.lu",
        sellerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        answer: "It not that difficult to remove the wrap...",
    },
    {
        id: 3,
        askerName: "kvo",
        askerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        askerScore: "+7",
        question:
            "On the pictures, the color near the trunk — is it the original or the wrap?",
        sellerName: "Raymondu.lu",
        sellerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        answer: "Yes, partially original. The trunk area was left unwrapped.",
    },
    {
        id: 4,
        askerName: "User4",
        askerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        askerScore: "+5",
        question: "Another question example?",
        sellerName: "Raymondu.lu",
        sellerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        answer: "Answer for Q&A 4.",
    },
    {
        id: 5,
        askerName: "User5",
        askerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        askerScore: "+3",
        question: "What about the car's maintenance history?",
        sellerName: "Raymondu.lu",
        sellerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        answer: "The maintenance records are available upon request.",
    },
    {
        id: 6,
        askerName: "User6",
        askerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        askerScore: "+1",
        question: "Is there any damage reported?",
        sellerName: "Raymondu.lu",
        sellerImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        answer: "No significant damage has been reported.",
    },
];


export const DUMMY_BIDS = [
    {
        id: 1,
        bidderName: "deepseaman22",
        bidderImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        bidderScore: "+22",
        bidAmount: 4250,
        bidTime: "1d",
    },
    {
        id: 2,
        bidderName: "donpedro1",
        bidderImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        bidderScore: "+225",
        bidAmount: 4150,
        bidTime: "1d",
    },
    {
        id: 3,
        bidderName: "deepseaman22",
        bidderImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        bidderScore: "+22",
        bidAmount: 4250,
        bidTime: "2d",
    },
    {
        id: 4,
        bidderName: "donpedro1",
        bidderImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        bidderScore: "+225",
        bidAmount: 4150,
        bidTime: "3d",
    },
    {
        id: 5,
        bidderName: "deepseaman22",
        bidderImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        bidderScore: "+22",
        bidAmount: 4250,
        bidTime: "4d",
    },
    {
        id: 6,
        bidderName: "donpedro1",
        bidderImage:
            "https://vntrade.edu.vn/wp-content/uploads/2025/02/avatar-natra.webp",
        bidderScore: "+225",
        bidAmount: 4150,
        bidTime: "5d",
    },
];